project:
  type: website
  output-dir: docs

website:
  title: "RRLing"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: team.qmd
        text: "Team"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

callout-icon: false

